import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';

interface PODData {
  id: number;
  companyName: string;
  driverName: string;
  vehicleVrm?: string;
  customerName: string;
  deliveryAddress?: string;
  referenceNumber?: string;
  deliveryNotes?: string;
  gpsLatitude: string;
  gpsLongitude: string;
  gpsAccuracy?: number;
  completedAt: string;
  status: string;
  photoCount: number;
  hasSignature: boolean;
}

export function generatePODPdf(data: PODData): PassThrough {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const stream = new PassThrough();
  doc.pipe(stream);

  const completedDate = new Date(data.completedAt);
  const dateStr = completedDate.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric'
  });
  const timeStr = completedDate.toLocaleTimeString('en-GB', {
    hour: '2-digit',
    minute: '2-digit'
  });

  doc.fontSize(22).font('Helvetica-Bold').text('PROOF OF DELIVERY', { align: 'center' });
  doc.moveDown(0.5);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#dddddd');
  doc.moveDown(1);

  doc.fillColor('#000000');
  doc.fontSize(12).font('Helvetica-Bold').text('Company: ', { continued: true }).font('Helvetica').text(data.companyName);
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Delivery Details', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').text('Customer: ', { continued: true }).font('Helvetica').text(data.customerName);
  doc.fontSize(12).font('Helvetica-Bold').text('Address: ', { continued: true }).font('Helvetica').text(data.deliveryAddress || 'Not provided');
  doc.fontSize(12).font('Helvetica-Bold').text('Reference: ', { continued: true }).font('Helvetica').text(data.referenceNumber || 'N/A');
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Driver & Vehicle', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').text('Driver: ', { continued: true }).font('Helvetica').text(data.driverName);
  doc.fontSize(12).font('Helvetica-Bold').text('Vehicle VRM: ', { continued: true }).font('Helvetica').text(data.vehicleVrm || 'N/A');
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Date & Time', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').text('Completed: ', { continued: true }).font('Helvetica').text(`${dateStr} ${timeStr}`);
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Location', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').text('GPS Coordinates: ', { continued: true }).font('Helvetica').text(`${data.gpsLatitude}, ${data.gpsLongitude}`);
  if (data.gpsAccuracy != null) {
    doc.fontSize(12).font('Helvetica-Bold').text('Accuracy: ', { continued: true }).font('Helvetica').text(`±${data.gpsAccuracy}m`);
  }
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Delivery Notes', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(11).font('Helvetica').text(data.deliveryNotes || 'No notes provided');
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Evidence', { underline: true });
  doc.moveDown(0.3);
  doc.fontSize(12).font('Helvetica-Bold').text('Signature: ', { continued: true }).font('Helvetica').text(data.hasSignature ? 'Captured electronically' : 'Not captured');
  doc.fontSize(12).font('Helvetica-Bold').text('Photos: ', { continued: true }).font('Helvetica').text(`${data.photoCount} attached`);
  doc.moveDown(1);

  doc.fontSize(14).font('Helvetica-Bold').text('Status', { underline: true });
  doc.moveDown(0.3);
  const statusColor = data.status === 'completed' ? '#16a34a' : data.status === 'invoiced' ? '#2563eb' : '#6b7280';
  doc.fontSize(12).font('Helvetica-Bold').fillColor(statusColor).text(data.status.charAt(0).toUpperCase() + data.status.slice(1));
  doc.fillColor('#000000');
  doc.moveDown(2);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#dddddd');
  doc.moveDown(1);

  const generatedDate = new Date().toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });
  doc.fontSize(9).fillColor('#666666').text(`Generated by Titan Fleet on ${generatedDate}`, { align: 'center' });
  doc.text('Records retained for 18 months (DVSA compliance)', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(8).text('This is a digitally generated document', { align: 'center' });

  doc.end();
  return stream;
}
