import { db } from "../server/db";
import { companies, users, vehicles, operatorLicences } from "../shared/schema";
import { eq } from "drizzle-orm";

async function importABTSO() {
  console.log("=== ABTSO Bulk Import ===\n");

  // 1. Create company
  console.log("1. Creating company ABTSO...");
  const [company] = await db.insert(companies).values({
    companyCode: "ABTSO",
    name: "ABTSO",
    licenseTier: "operator",
    vehicleAllowance: 60,
    contactEmail: "monikaabtso@gmail.com",
    settings: {
      poolFleet: true,
      showFuelPrices: false,
      requireFuelCardPhoto: true,
      enableEndOfShiftCheck: false,
      fuelEnabled: true,
      adblueEnabled: true,
      collisionsEnabled: true,
      podEnabled: true,
      driverHistoryDays: 7,
      fuelAnomalyThreshold: 2.0
    }
  }).returning();
  console.log(`  Company created: ID=${company.id}, Code=ABTSO\n`);

  const companyId = company.id;

  // 2. Import vehicles
  console.log("2. Importing vehicles...");
  const vehicleData = [
    { vrm: "A25DTP", make: "MAN", model: "TGX 26.460 6X2/2 BLS", mileage: 891030, category: "DLLP" },
    { vrm: "BT71TVM", make: "MAN", model: "TGX (MY2018)", mileage: 784013, category: "Zald Transport" },
    { vrm: "BT71TVN", make: "MAN", model: "TGX (MY2018)", mileage: 788598, category: "TBEX" },
    { vrm: "DA22YKP", make: "MAN", model: "TGX (MY2018)", mileage: 689592, category: "TBEX" },
    { vrm: "DA22YKU", make: "MAN", model: "TGX (MY2018)", mileage: 567051, category: "Sebastiannicola LTD" },
    { vrm: "DA22YKW", make: "MAN", model: "TGX (MY2018)", mileage: 584681, category: "Sebastiannicola LTD" },
    { vrm: "DA22YMM", make: "MAN", model: "TGX (MY2018)", mileage: 680997, category: "TBEX" },
    { vrm: "DC19GVZ", make: "MAN", model: "TGX", mileage: 773149, category: "Dzik LTD" },
    { vrm: "DC19HDG", make: "MAN", model: "TGX", mileage: 725008, category: "Sebastiannicola LTD" },
    { vrm: "DE22NNX", make: "MAN", model: "TGX (MY2018)", mileage: 572404, category: "TBEX" },
    { vrm: "DE69ZLU", make: "MAN", model: "TGX (MY2018)", mileage: 708400, category: "FEBE LTD" },
    { vrm: "DF19FRZ", make: "MAN", model: "TGX", mileage: 732864, category: "DPLLS" },
    { vrm: "DK17LBO", make: "MAN", model: "TGX", mileage: 9742438, category: "DPLLS" },
    { vrm: "DK17LHL", make: "MAN", model: "TGX 26.460 6X2/2 BLS", mileage: 738865, category: "TKM Logistics" },
    { vrm: "DK18HKH", make: "DAF TRUCKS", model: "XF", mileage: 953503, category: "J&K Haulage" },
    { vrm: "EY66MZF", make: "MAN", model: "TGX", mileage: 764200, category: "NEXURA" },
    { vrm: "FD66NMX", make: "DAF TRUCKS", model: "XF", mileage: 980424, category: "Doncaster Truck Parts" },
    { vrm: "FJ69ZWG", make: "DAF TRUCKS", model: "XF", mileage: 690448, category: "FEBE LTD" },
    { vrm: "FL19VFK", make: "DAF TRUCKS", model: "XF", mileage: 958989, category: "ATOZ" },
    { vrm: "FN19EPY", make: "DAF TRUCKS", model: "CF", mileage: 507483, category: "Rafpis" },
    { vrm: "FN19EZM", make: "DAF TRUCKS", model: "XF", mileage: 895206, category: "Sebastiannicola LTD" },
    { vrm: "FP64SRZ", make: "DAF TRUCKS", model: "CF", mileage: 882223, category: "ATOZ" },
    { vrm: "FP66YPA", make: "DAF TRUCKS", model: "CF", mileage: 6551972, category: "NEXURA" },
    { vrm: "FP68LFV", make: "DAF TRUCKS", model: "XF", mileage: 922043, category: "ATOZ" },
    { vrm: "FP68LJK", make: "DAF TRUCKS", model: "CF", mileage: 843797, category: "FEBE LTD" },
    { vrm: "G17DCN", make: "MAN", model: "TGS", mileage: 873958, category: "TFL" },
    { vrm: "K12DCN", make: "MAN", model: "TGX", mileage: 104443, category: "TFL" },
    { vrm: "K26DCN", make: "DAF TRUCKS", model: "CF", mileage: 900443, category: "DPLLS" },
    { vrm: "K31DCN", make: "MAN", model: "TGX", mileage: 891523, category: "TFL" },
    { vrm: "K33DCN", make: "MAN", model: "TGS", mileage: 51765, category: "TFL" },
    { vrm: "KX17MLF", make: "DAF TRUCKS", model: "XF", mileage: 787864, category: "Rafpis" },
    { vrm: "KY19HEU", make: "DAF TRUCKS", model: "XF", mileage: 851051, category: "DLPX" },
    { vrm: "MV15CGY", make: "MAN", model: "TGX", mileage: 987678, category: "DLLP" },
    { vrm: "NX68UJH", make: "MAN", model: "TGX", mileage: 579619, category: "TFL" },
    { vrm: "NX68UJL", make: "MAN", model: "TGX", mileage: 676792, category: "TFL" },
    { vrm: "PN17OML", make: "MAN", model: "TGS", mileage: 759960, category: "TKM Logistics" },
    { vrm: "PN17ONF", make: "MAN", model: "TGS", mileage: 891195, category: "TKM Logistics" },
    { vrm: "PX18HXO", make: "DAF TRUCKS", model: "XF", mileage: 951287, category: "Radek Trade LTD" },
    { vrm: "RA15OOX", make: "DAF TRUCKS", model: "CF", mileage: 796582, category: "Chekorsco Services LTD" },
    { vrm: "RX68YYO", make: "DAF TRUCKS", model: "CF", mileage: 659610, category: "DLPX" },
    { vrm: "SF65ZSO", make: "MAN", model: "TGX", mileage: 116927, category: "Rafpis" },
    { vrm: "SV68NCF", make: "MAN", model: "TGX", mileage: 974455, category: "ATOZ" },
    { vrm: "VX69YFP", make: "DAF TRUCKS", model: "XF", mileage: 830651, category: "TBEX" },
    { vrm: "VX69YFR", make: "DAF TRUCKS", model: "XF", mileage: 801992, category: "DSA" },
    { vrm: "WH69JUU", make: "MAN", model: "TGX (MY2018)", mileage: 1271366, category: "FEBE LTD" },
    { vrm: "YE67UYR", make: "DAF TRUCKS", model: "CF", mileage: 809919, category: "Konrad Travel LTD" },
    { vrm: "YS17NTY", make: "DAF TRUCKS", model: "CF", mileage: 627969, category: "DPLLS" },
    { vrm: "YX16DKJ", make: "RENAULT TRUCKS", model: "T (T)", mileage: 804332, category: "J&K Haulage" },
    { vrm: "YX68OAJ", make: "DAF TRUCKS", model: "XF", mileage: 801384, category: "DSA" },
  ];

  const insertedVehicles = await db.insert(vehicles).values(
    vehicleData.map(v => ({
      companyId,
      vrm: v.vrm,
      make: v.make,
      model: v.model,
      vehicleCategory: "HGV",
      currentMileage: v.mileage,
      fleetNumber: v.category,
      active: true,
    }))
  ).returning();
  console.log(`  Imported ${insertedVehicles.length} vehicles\n`);

  // 3. Import drivers (deduplicated by email)
  console.log("3. Importing drivers...");
  const driverData = [
    { name: "Adam Oman", phone: "+447754566535", email: "adam.omen84@gmail.com" },
    { name: "Adelin Bejan", phone: null, email: "adelinbejan2.0@gmail.com" },
    { name: "Adrian Szostak", phone: null, email: "stasiek0187@gmail.com" },
    { name: "Aleksy Kuzniarek", phone: null, email: "kuzniarek22@icloud.com" },
    { name: "Aleksy Wikira", phone: null, email: "alexwikira@gmail.com" },
    { name: "Alister Nightingale", phone: "+447950367598", email: "alistern2130@gmail.com" },
    { name: "Anatolie Gaidau", phone: null, email: "anatoliegaidau6@gmail.com" },
    { name: "Andrzej Ejmocki", phone: null, email: "ejmockiandrzej6@gmail.com" },
    { name: "Andrzej Suprun", phone: "+447783354222", email: "andrzejsup89@gmail.com" },
    { name: "Andrzej Szczesniak", phone: null, email: "ziutek969@gmail.com" },
    { name: "Anees Iftikhar", phone: null, email: "iftikharanees3028@gmail.com" },
    { name: "Arhip Papuc", phone: "+447838119704", email: "slipper.archie@gmail.com" },
    { name: "Arkadiusz Lecki", phone: "+447719770719", email: "arkadio1213@gmail.com" },
    { name: "Arkadiusz Wozniak", phone: "+447561376891", email: "arikos30@poczta.fm" },
    { name: "Artur Zylinski", phone: "+447426554242", email: "arturzylinski5@gmail.com" },
    { name: "Balan Florin", phone: "+447401844696", email: "balanflorin92b_27@yahoo.com" },
    { name: "Bartlomiej Dziembowski", phone: "+447385451323", email: "dziembowskibartek@gmail.com" },
    { name: "Bartlomiej Potyralski", phone: null, email: "potyralskibartek616@gmail.com" },
    { name: "Bartosz Chetkowski", phone: "+44750490599", email: "b.chetkowski@gmail.com" },
    { name: "Bethi Faycal", phone: "+447470152812", email: "bethifaysal@gmail.com" },
    { name: "Blazej Renski", phone: "+447578637676", email: "roniu@o2.pl" },
    { name: "Bogdan Ciobanu", phone: null, email: "ceobanub@yahoo.com" },
    { name: "Chad Webb", phone: "+447860961944", email: "Chadwebb1998@hotmail.co.uk" },
    { name: "Christopher Oshea", phone: "+447784851765", email: "chrisoshea1401@gmail.com" },
    { name: "Constantin Alexandru Zamfir", phone: null, email: "calex873@yahoo.com" },
    { name: "Cosmin CIUCALAU", phone: "+447550535051", email: "cdcqualitytransport@gmail.com" },
    { name: "Cosmin Grigoras", phone: null, email: "cozamin2016@gmail.com" },
    { name: "Cosmin Marian Butarita", phone: null, email: "butarita.cosmin@gmail.com" },
    { name: "Damian Amerla", phone: null, email: "amerladamian@gmail.com" },
    { name: "Damian Krowinski", phone: "+447596107591", email: "damianko52@o2.pl" },
    { name: "Damian Melisa", phone: "+447449057700", email: "dpll@wp.pl" },
    { name: "Damian Sozanski", phone: null, email: "damiansozanski92@gmail.com" },
    { name: "Daniel Dabrowski", phone: "+447975717539", email: "drabinaa@interia.pl" },
    { name: "Daniel Plonowski", phone: "+447708349597", email: "lp.plonowski.ltd@gmail.com" },
    { name: "Daniel Przepiora", phone: "+447745172242", email: "danielprzepiora1996@gmail.com" },
    { name: "Dariusz Bekas", phone: "+447546610806", email: "darek.bekas23@gmail.com" },
    { name: "Dariusz Jagielo", phone: "+447590494511", email: "dariuszjag7@yahoo.com" },
    { name: "Dariusz Sochacki", phone: "+447549047476", email: "dasdriverlimited@gmail.com" },
    { name: "Dariusz Trzeciak", phone: null, email: "jdtltd1@gmail.com" },
    { name: "Dawid Anzorge", phone: "+447591835965", email: "dahireltd@gmail.com" },
    { name: "Dawid Szczepankiewicz", phone: "+447465800388", email: "planning@dsalogistics.co.uk" },
    { name: "Dawid Zybura", phone: null, email: "dpll.dawid@gmail.com" },
    { name: "Dean Hall", phone: null, email: "deanleehall@hotmail.com" },
    { name: "Denis Tcaciov", phone: "+447533848006", email: "kdt5@mail.ru" },
    { name: "Dieng Fallou", phone: null, email: "diengfallou@icloud.com" },
    { name: "Douglas Eli", phone: "+447405539536", email: "douanaeli2000@gmail.com" },
    { name: "Elrabea Ahmed", phone: "+44744636469", email: "mynameisrabea@gmail.com" },
    { name: "Emil Mucha", phone: "+447507951587", email: "emil.mucha69@gmail.com" },
    { name: "Emil Szymczak", phone: "+447548112576", email: "emilsz4891@gmail.com" },
    { name: "Fadhlaoui Seifallah", phone: "+447760669010", email: "seiflorraine96@gmail.com" },
    { name: "FerencGabriel Cretu", phone: "+447912868257", email: "Gabriel.cretu90@gmail.com" },
    { name: "Flavius-Ovidiu Giuchici", phone: "+447774944431", email: "flavivsoi123@gmail.com" },
    { name: "Gheorghe Mihai", phone: "+447482113655", email: "gheorghemihai005@gmail.com" },
    { name: "Grzegorz Mozdzen", phone: "+447463949492", email: "mgr4logistic@gmail.com" },
    { name: "Grzegorz Pawlowski", phone: null, email: "huragan116@yahoo.com" },
    { name: "Igors Baranovskis", phone: "+447495173294", email: "Igorsb987@gmail.com" },
    { name: "Ionel Birica-Angel", phone: null, email: "ibirica91@yahoo.com" },
    { name: "Ireneusz Miotk", phone: "+447576703903", email: "irek.miotk@gmail.com" },
    { name: "Ireneusz Szelka", phone: "+447450077208", email: "erikszelka@yahoo.com" },
    { name: "Iulian-Ionut Avram", phone: "+447450974103", email: "ionutavram@yahoo.com" },
    { name: "Jacek Bedzinski", phone: "+447519273223", email: "drooops78@gmail.com" },
    { name: "Jacek Gast", phone: null, email: "gastjacek1@gmail.com" },
    { name: "Jacek Sitarz", phone: "+447563709666", email: "iwo.jack@yahoo.com" },
    { name: "Jacek Wojcik", phone: "+447587612350", email: "jack.wojcik70@gmail.com" },
    { name: "Jakub Ciezki", phone: "+447961061314", email: "jakubciezki@op.pl" },
    { name: "Jakub Rybinski", phone: null, email: "kubaryba199090@gmail.com" },
    { name: "Jakub Sozanski", phone: null, email: "kubik2k15@gmail.com" },
    { name: "James Mcardle", phone: null, email: "jameswmcardle@hotmail.com" },
    { name: "Jan Kowalczuk", phone: null, email: "mexyk@yahoo.com" },
    { name: "Janis Irmans", phone: "+447435189267", email: "printer102@inbox.lv" },
    { name: "Jaroslaw Golicz", phone: "+447852711889", email: "jaro82ltd@gmail.com" },
    { name: "Jaroslaw Palczynski", phone: "+447476523659", email: "jaras.1981@o2.pl" },
    { name: "Jaroslaw Raban", phone: "+447707962265", email: "jarekrab09@gmail.com" },
    { name: "Jerzy Wilczynski", phone: "+447707519909", email: "smyk5388@gmail.com" },
    { name: "John Byrne", phone: null, email: "jonbyrne10@googlemail.com" },
    { name: "Jonathan Rissbrook", phone: "+447361755191", email: "JRissbrook73@gmail.com" },
    { name: "Kacper Blechacz", phone: null, email: "kacper.blechacz123@gmail.com" },
    { name: "Kamil Gazdzicki", phone: null, email: "kamil.j.gazdzicki@gmail.com" },
    { name: "Kamil Kiedynk", phone: "+447401701583", email: "kamilkiedynk@gmail.com" },
    { name: "Kamil Matuszewicz", phone: null, email: "kamil.matu59@gmail.com" },
    { name: "Kamil Turek", phone: "+447562485076", email: "kamilturek1@o2.pl" },
    { name: "Kamil Walinowicz", phone: null, email: "arminek1205@gmail.com" },
    { name: "Kamil Wrona", phone: "+447708522475", email: "nkwrenovations@yahoo.com" },
    { name: "Kamil Wysocki", phone: "+447473324759", email: "rudy2044@gmail.com" },
    { name: "Karolina Suprun", phone: null, email: "kapilipczuk@gmail.com" },
    { name: "Konrad Dudlak", phone: null, email: "konrad.dudlak@gmail.com" },
    { name: "Kornel Januszewski", phone: "+447849348232", email: "kornel.januszewski@gmail.com" },
    { name: "Krzysztof Czaja", phone: null, email: "czajakrzysztof@protonmail.com" },
    { name: "Krzysztof Gawot", phone: null, email: "gawotkrzysztof@gmail.com" },
    { name: "Krzysztof Koscielak", phone: "+447840009334", email: "kristrans1980@gmail.com" },
    { name: "Krzysztof Kuzma", phone: "+447863666893", email: "tolo103@interia.pl" },
    { name: "Krzysztof Libigocki", phone: null, email: "libigocki@gmail.com" },
    { name: "Krzysztof Sielezin", phone: "+447871486914", email: "sielu31@wp.pl" },
    { name: "Krzysztof Suprun", phone: null, email: "krzysztofsuprun1986@gmail.com" },
    { name: "Krzysztof Turski", phone: null, email: "turskik87@gmail.com" },
    { name: "Lee Wharam", phone: null, email: "leewharam81@gmail.com" },
    { name: "Leslaw Chudy", phone: "+447825745088", email: "Lwctransportltd2014@yahoo.com" },
    { name: "Lukasz Ciesielski", phone: "+447575101155", email: "bl4oll@gmail.com" },
    { name: "Lukasz Kurek", phone: "+447935604342", email: "aress84@gmail.com" },
    { name: "Lukasz Majstruk", phone: null, email: "lukaszmajstruk1983@gmail.com" },
    { name: "Lukasz Pilch", phone: null, email: "pilchlukasz83@gmail.com" },
    { name: "Lukasz Stelmaszek", phone: null, email: "lukasz.stelmaszek@gmail.com" },
    { name: "Lukasz Tomkow", phone: "+447448840192", email: "lukasztomkow@interia.eu" },
    { name: "Lukasz Tuzim", phone: null, email: "tuzimpl89@gmail.com" },
    { name: "Lukasz Zielinski", phone: null, email: "lukasz2987@gmail.com" },
    { name: "Luqman Rasool", phone: null, email: "luqmanrasooluk@icloud.com" },
    { name: "Maciej Blechacz", phone: "+447544970184", email: "maciej@4camp.pl" },
    { name: "Maciej Lukojko", phone: "+447482248236", email: "majkelgryf@gmail.com" },
    { name: "Maciej Wardega", phone: null, email: "wargos.76@gmail.com" },
    { name: "Marcin Fryza", phone: "+447526164373", email: "marcinfryza@o2.pl" },
    { name: "Marcin Klajmon", phone: "+447572433365", email: "marcin.klajmon@yahoo.co.uk" },
    { name: "Marcin Nowak", phone: "+447367473377", email: "nowakmarcin158@gmail.com" },
    { name: "Marek Kopinski", phone: "+447891511962", email: "marcycha.kopek@gmail.com" },
    { name: "Marek Krzyszkowski", phone: null, email: "donnyhaulage@gmail.com" },
    { name: "Marek Simelevic", phone: "+447999259674", email: "markizaut@gmail.com" },
    { name: "Marewan Hamad", phone: null, email: "hamadmarewan69@gmail.com" },
    { name: "Marian Petcof", phone: null, email: "Petcof.marian@gmail.com" },
    { name: "Marian Popescu", phone: null, email: "marianpopescu2038@gmail.com" },
    { name: "Mariusz Idzik", phone: "+447956785509", email: "mazgiles@gmail.com" },
    { name: "Mariusz Kocinski", phone: "+447438561223", email: "Mk.group1916@gmail.com" },
    { name: "Mariusz Siczuk", phone: "+447552774446", email: "mariusz.siczuk@gmail.com" },
    { name: "Mariusz Sierociuk", phone: "+447429880662", email: "mariusz.sierociuk@gmail.com" },
    { name: "Mariusz Wojtacki", phone: "+447502378893", email: "Mariusz.Wojtacki@gmail.com" },
    { name: "Mateusz Gierlach", phone: "+447413367223", email: "vvati@o2.pl" },
    { name: "Mateusz Koziel", phone: "+447727333272", email: "mativip1@poczta.fm" },
    { name: "Mateusz Malczyk", phone: "+447818666764", email: "mateusz.malczyk@gmail.com" },
    { name: "Michael-Stephen Payne", phone: "+447380599510", email: "mikepayne144@protonmail.com" },
    { name: "Michal Kosakowski", phone: "+447545362549", email: "michal.kosakowski.ols@gmail.com" },
    { name: "Michal Mielczarek", phone: "+447713282342", email: "michalmielczarek88@gmail.com" },
    { name: "Michal Padysz", phone: "+447532671022", email: "turbojotej@gmail.com" },
    { name: "Michal Piotrowski", phone: null, email: "sierra2271@gmail.com" },
    { name: "Mihaela Cristea", phone: null, email: "zaramihaela52@yahoo.com" },
    { name: "Mihaela Grigoras", phone: null, email: "sebcosmi7@yahoo.com" },
    { name: "Mihai Rotaru", phone: null, email: "rotaru.mihai@libero.it" },
    { name: "Mikolaj Blechacz", phone: "+447544970184", email: "mikib24@gmail.com" },
    { name: "Miroslaw Gruszfeld", phone: "+447541309160", email: "mirekgruszfeld0@gmail.com" },
    { name: "Modou Kara Diouck", phone: null, email: "karadiouck10@gmail.com" },
    { name: "Monika Szastaj", phone: null, email: "monikarelay@gmail.com" },
    { name: "Monika Szczepanska", phone: null, email: "monikaabtso@gmail.com" },
    { name: "Nicolae Boaza", phone: null, email: "rboaza89@gmail.com" },
    { name: "Oskar Zgorzelski", phone: null, email: "oscaerzgorzelski@gmail.com" },
    { name: "Patryk Balinski", phone: "+447724605482", email: "patrykbalinski@yahoo.com" },
    { name: "Pawel Brylka", phone: null, email: "pawelbryka04@gmail.com" },
    { name: "Pawel Grabowski", phone: "+447915180178", email: "grabowski.flt@gmail.com" },
    { name: "Pawel Jurkiewicz", phone: null, email: "paweljurkiewicz29@gmail.com" },
    { name: "Pawel Korzeniowski", phone: null, email: "korzon85@gmail.com" },
    { name: "Pawel Topolewski", phone: "+447440674114", email: "p.topolewskii@gmail.com" },
    { name: "Pawel Wieckowski", phone: null, email: "p.wieckowski83@gmail.com" },
    { name: "Piotr Pietrzak", phone: "+447842742646", email: "piotr.peste@gmail.com" },
    { name: "Przemyslaw Feruga", phone: "+447835351902", email: "peterferuga@gmail.com" },
    { name: "Przemyslaw Grabowski", phone: "+447761364260", email: "przemyslawgrabowskiltd@gmail.com" },
    { name: "Przemyslaw Woszczyk", phone: null, email: "przemekwo1984@gmail.com" },
    { name: "Qasim-Ali Shah", phone: "+447367273793", email: "shahboystransport@gmail.com" },
    { name: "Radoslaw Kubaszewski", phone: null, email: "radoslaw.kubaszewski@mail.com" },
    { name: "Rafal Biskup", phone: "+447828444414", email: "rafalbiskup88@gmail.com" },
    { name: "Rafal Kwiatkowski", phone: "+447401628068", email: "kolpak65@wp.pl" },
    { name: "Rafal Majcher", phone: "+447892720260", email: "Ralfvip@interia.pl" },
    { name: "Rafal Pisarczyk", phone: "+447706610422", email: "pisak1991@gmail.com" },
    { name: "Rafal Zawislak", phone: null, email: "rzawislak13@gmail.com" },
    { name: "Robert Armknecht", phone: "+447742800417", email: "robert.czepek@gmail.com" },
    { name: "Robert Bekas", phone: "+447761396385", email: "abtsorobert@gmail.com" },
    { name: "Robert Zgodzinski", phone: "+447598456823", email: "robert61zgoda@gmail.com" },
    { name: "Robert Zuraw", phone: "+447724410106", email: "Mrzuraw@wp.pl" },
    { name: "Roger Wawszczak", phone: null, email: "roger.waw.ltd@gmail.com" },
    { name: "Romualds Dargels", phone: null, email: "romi411@inbox.lv" },
    { name: "Sebastian Czaplicki", phone: "+447508120936", email: "czapa102@aol.com" },
    { name: "Sebastian Borek", phone: "+447712194975", email: "asborek@hotmail.com" },
    { name: "Sebastian Kosinski", phone: "+447864316852", email: "kosinskiseba0809@gmail.com" },
    { name: "Slawomir Mackiewicz", phone: "+447442373135", email: "macasuwalki@gmail.com" },
    { name: "Slawomir Nowotnik", phone: null, email: "nslawas@gmail.com" },
    { name: "Smail Mulahmetovic", phone: "+447827814017", email: "Smailmulahmetovic@gmail.com" },
    { name: "Stanislaw Potyralski", phone: "+447477705528", email: "stanleypotyralski1@gmail.com" },
    { name: "Tomasz Bobiec", phone: "+447450222822", email: "ktptomas@gmail.com" },
    { name: "Tomasz Czabaj", phone: null, email: "tomaszczabaj@googlemail.com" },
    { name: "Tomasz Czyzewski", phone: null, email: "tomasocz72@gmail.com" },
    { name: "Tomasz Lewandowski", phone: "+447401714410", email: "topalew@gmail.com" },
    { name: "Valentin Irimia", phone: "+447459823430", email: "irimia185@gmail.com" },
    { name: "Valy Bostan", phone: null, email: "valysorin2024@gmail.com" },
    { name: "Vasile-Daniel Carstea", phone: "+447838495204", email: "vasilecarstea2020@gmail.com" },
    { name: "Viktors Kononovics", phone: "+447963708414", email: "Kononvictor@gmail.com" },
    { name: "Wojciech Erfort", phone: null, email: "erfortwojtek900@gmail.com" },
    { name: "Wojciech Sobecki", phone: "+447541288279", email: "wwojtek.sobecki@gmail.com" },
    { name: "Zubeyr Hassan", phone: null, email: "zubeir_11@hotmail.com" },
    { name: "Martyna Szczepankiewicz", phone: null, email: "martyna.szczepankiewicz@abtso.com" },
  ];

  const seenEmails = new Set<string>();
  const uniqueDrivers = driverData.filter(d => {
    const emailLower = d.email.toLowerCase();
    if (seenEmails.has(emailLower)) return false;
    seenEmails.add(emailLower);
    return true;
  });

  const insertedDrivers = await db.insert(users).values(
    uniqueDrivers.map(d => ({
      companyId,
      email: d.email,
      name: d.name,
      role: "DRIVER" as const,
      phone: d.phone,
      active: true,
    }))
  ).returning();
  console.log(`  Imported ${insertedDrivers.length} unique drivers (deduplicated from ${driverData.length})\n`);

  // 4. Import O-Licences
  console.log("4. Importing O-Licences...");
  const licenceData = [
    {
      licenceNumber: "OB2076394",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2024-10-22"),
      reviewDate: new Date("2029-09-30"),
      authorisedVehicles: 4,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "6 weeks",
    },
    {
      licenceNumber: "OB2075539",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2024-10-08"),
      reviewDate: new Date("2029-06-30"),
      authorisedVehicles: 4,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "6 weeks",
    },
    {
      licenceNumber: "OB2074977",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: null,
      reviewDate: null,
      authorisedVehicles: 0,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "None",
    },
    {
      licenceNumber: "OB2072360",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2024-06-21"),
      reviewDate: new Date("2029-06-30"),
      authorisedVehicles: 2,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "6 weeks",
    },
    {
      licenceNumber: "OB2062375",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "International",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2023-05-11"),
      reviewDate: new Date("2028-04-30"),
      authorisedVehicles: 5,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "6 weeks",
    },
    {
      licenceNumber: "OB2059801",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2022-10-13"),
      reviewDate: new Date("2027-09-30"),
      authorisedVehicles: 4,
      authorisedTrailers: 0,
      safetyInspectionFrequency: "6 weeks",
    },
    {
      licenceNumber: "OB2024306",
      trafficArea: "North-Eastern Traffic Area",
      licenceType: "Restricted",
      vehicleCategory: "HGV",
      inForceFrom: new Date("2019-07-08"),
      reviewDate: new Date("2029-06-30"),
      authorisedVehicles: 10,
      authorisedTrailers: 8,
      safetyInspectionFrequency: "6 weeks",
    },
  ];

  const insertedLicences = await db.insert(operatorLicences).values(
    licenceData.map(l => ({
      companyId,
      licenceNumber: l.licenceNumber,
      trafficArea: l.trafficArea,
      licenceType: l.licenceType,
      vehicleCategory: l.vehicleCategory,
      inForceFrom: l.inForceFrom,
      reviewDate: l.reviewDate,
      authorisedVehicles: l.authorisedVehicles,
      authorisedTrailers: l.authorisedTrailers,
      safetyInspectionFrequency: l.safetyInspectionFrequency,
      active: true,
    }))
  ).returning();
  console.log(`  Imported ${insertedLicences.length} O-Licences\n`);

  // Summary
  console.log("=== Import Complete ===");
  console.log(`Company: ABTSO (ID: ${companyId})`);
  console.log(`Vehicles: ${insertedVehicles.length}`);
  console.log(`Drivers: ${insertedDrivers.length}`);
  console.log(`O-Licences: ${insertedLicences.length}`);
  console.log(`Total authorised vehicles across licences: ${licenceData.reduce((sum, l) => sum + l.authorisedVehicles, 0)}`);
}

importABTSO()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Import failed:", err);
    process.exit(1);
  });
